# Font
font_family      Hack Nerd Font
bold_font        Hack Nerd Font Bold
italic_font      Hack Nerd Font Italic
font_size        12.0

# Layouts
enabled_layouts splits
# Vertical split
map ctrl+shift+k launch --location=vsplit --cwd=current
# Horizontal split
map ctrl+shift+l launch --location=hsplit --cwd=current

# Colors
background       #000000
foreground       #ffffff
selection_background #1e1e1e
selection_foreground #eeeeee

# Bright colors
color8   #555555
color9   #ff6e6e
color10  #72ff72
color11  #ffee80
color12  #81aaff
color13  #f685ff
color14  #7fffff
color15  #ffffff

# Other
mouse_map right click ungrabbed copy_to_clipboard
enable_audio_bell no
hide_window_decorations yes
